spring.application.name=ReportDemoApp
server.port=8081

keycloak.realm=reports-realm
keycloak.auth-server-url=http://keycloak:8080
keycloak.resource=reports-api
keycloak.credentials.secret=oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq
keycloak.bearer-only=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/reports-realm

logging.level.org.springframework.security=TRACE
logging.level.org.keycloak=TRACE
logging.level.org.springframework.security.oauth2.jwt=TRACE
logging.level.org.springframework.security.oauth2.server.resource.authentication=TRACE